name: flutter_capstone2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  go_router:
  cupertino_icons:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/images/capstoneAppIcon.png
    -  assets/images/profilePic.png
    -  assets/images/capstoneAudioPic.png
    -  assets/images/capstonePodcastPic.png
    -  assets/images/capstoneFairyTallePic1.png
    -  assets/images/capstoneFairyTallePic2.png
